services:
  job-app:
    container_name: job-app
    image: ghcr.io/meisdy/job-app:latest
    build: .
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./update.sh:/deploy/update.sh
    restart: unless-stopped
    command: sh -c "[ -f /deploy/update.sh ] && cp /app/update.sh /deploy/update.sh; exec ./Job_App"
