services:
  job-app:
    container_name: job-app
    image: ghcr.io/meisdy/job-app:latest
    build: .
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
