// Client-side geocoder for Swiss job locations.
// Data: frontend/data/ch-geo.json, generated by scripts/build-geo-json.mjs.
// All lookup logic lives here — map.js only calls locate(). If coordinates
// ever get promoted into the database, this module is the single port target.

// Fold to a comparable key: lowercase, strip accents, collapse punctuation.
// The build script imports this function, so build and runtime share one copy.
export function normalizePlace(raw) {
  return raw
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

// Place strings mix formats — "Biel/Bienne", "Luzern / hybrid", "Kriens
// (Luzern)", "Geneva, Geneva, Switzerland" — every part is a match chance.
// Parentheses become separators so their content survives as a fallback.
function placeSegments(raw) {
  return raw
    .replace(/[()]/g, ',')
    .split(/[,/]/)
    .map(normalizePlace)
    .filter(Boolean);
}

export function createGeocoder(geoData) {
  const { zip, name, alias } = geoData;

  function lookupName(key) {
    const resolved = alias[key] || key;
    return name[resolved] || null;
  }

  // Region prefixes hide the locality behind a filler word ("Region Bern",
  // "Greater Zurich Area") — the shrink below only drops words from the right.
  const LEADING_FILLER = new Set(['region', 'kanton', 'canton', 'greater']);

  // Try each segment full first, then shrink from the right one word at a
  // time: the primary locality comes first in every observed place format
  // ("Weggis Luzern", "Zürich Metropolitan Area", "Baden-Daettwil").
  function locateByPlace(place) {
    for (const segment of placeSegments(place)) {
      let words = segment.split(' ');
      if (words.length > 1 && LEADING_FILLER.has(words[0])) words = words.slice(1);
      for (let length = words.length; length >= 1; length--) {
        const hit = lookupName(words.slice(0, length).join(' '));
        if (hit) return hit;
      }
    }
    return null;
  }

  return {
    // job needs .zipcode and .place; returns { lat, lon, method } or null
    locate(job) {
      if (job.zipcode) {
        const hit = zip[String(job.zipcode).trim()];
        if (hit) return { lat: hit[0], lon: hit[1], method: 'zipcode' };
      }
      if (job.place) {
        // Some sources embed the zip in the place string ("1207 Genève")
        const embeddedZip = job.place.match(/\b(\d{4})\b/);
        const zipHit = embeddedZip && zip[embeddedZip[1]];
        if (zipHit) return { lat: zipHit[0], lon: zipHit[1], method: 'zipcode' };

        const hit = locateByPlace(job.place);
        if (hit) return { lat: hit[0], lon: hit[1], method: 'name' };
      }
      return null;
    }
  };
}
